# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Probando2"
client_id = "b79dcc65e8574ebd53ddf47b16f73c57"
application_url = "https://customs-intention-hub-author.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://customs-intention-hub-author.trycloudflare.com/auth/callback",
  "https://customs-intention-hub-author.trycloudflare.com/auth/shopify/callback",
  "https://customs-intention-hub-author.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "inmers.myshopify.com"
